In [ ]:
1. Importar Librerías y Cargar los Datos
(Primera Celda)

In [12]:
# Importar librerías necesarias
import pandas as pd
import numpy as np
from fastapi import FastAPI
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import nest_asyncio
from uvicorn import run

# Cargar los datasets
df_movies = pd.read_csv("movies_dataset.csv", low_memory=False)
df_credits = pd.read_csv("credits.csv")

2. Exploración Inicial de los Datos (EDA)
(Segunda Celda)

In [13]:
# Mostrar las primeras filas de los datasets
print("Primeras filas de df_movies:")
print(df_movies.head())

print("\nPrimeras filas de df_credits:")
print(df_credits.head())

# Información general de las columnas y tipos de datos
print("\nInformación de df_movies:")
print(df_movies.info())

print("\nInformación de df_credits:")
print(df_credits.info())

# Listar columnas de cada dataset
print("\nColumnas en df_movies:")
print(df_movies.columns)

print("\nColumnas en df_credits:")
print(df_credits.columns)

Primeras filas de df_movies:
   adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en
1                                   NaN   8844  tt0113497                en
2                                   NaN  15602  tt0113228                en
3                                   NaN  31357  tt0114885                en
4                                   NaN  11862  tt0113041                en

                original_title  \
0                    Toy Story
1                      Jumanji
2             Grumpier Old Men
3            Waiting to Exhale
4  Father of the Bride Part II

                                            overview  ... release_date  \
0  Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1  When siblings Judy and Peter discover an encha...  ...   1995-12-15
2  A family wedding reignites the ancient feud be...  ...   1995-12-22
3  Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4  Just when George Banks has recovered from his ...  ...   1995-02-10

       revenue runtime                                   spoken_languages  \
0  373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1  262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2          0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3   81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4   76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released                                                NaN
1  Released          Roll the dice and unleash the excitement!
2  Released  Still Yelling. Still Fighting. Still Ready for...
3  Released  Friends are the people who let you be yourself...
4  Released  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count
0                    Toy Story  False          7.7     5415.0
1                      Jumanji  False          6.9     2413.0
2             Grumpier Old Men  False          6.5       92.0
3            Waiting to Exhale  False          6.1       34.0
4  Father of the Bride Part II  False          5.7      173.0

[5 rows x 24 columns]

Primeras filas de df_credits:
                                                cast  \
0  [{'cast_id': 14, 'character': 'Woody (voice)',...
1  [{'cast_id': 1, 'character': 'Alan Parrish', '...
2  [{'cast_id': 2, 'character': 'Max Goldman', 'c...
3  [{'cast_id': 1, 'character': "Savannah 'Vannah...
4  [{'cast_id': 1, 'character': 'George Banks', '...

                                                crew     id
0  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...    862
1  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...   8844
2  [{'credit_id': '52fe466a9251416c75077a89', 'de...  15602
3  [{'credit_id': '52fe44779251416c91011acb', 'de...  31357
4  [{'credit_id': '52fe44959251416c75039ed7', 'de...  11862

Información de df_movies:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB
None

Información de df_credits:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB
None

Columnas en df_movies:
Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

Columnas en df_credits:
Index(['cast', 'crew', 'id'], dtype='object')

reduccion df

In [14]:
# Tomar una muestra aleatoria del 50% del DataFrame de 'credits.csv'
df_credits = df_credits.sample(frac=0.5, random_state=42)

# Sobrescribir el archivo CSV original con la muestra aleatoria
df_credits.to_csv("credits.csv", index=False)

# Verificar las primeras filas para confirmar
print(df_credits.info())

<class 'pandas.core.frame.DataFrame'>
Index: 22738 entries, 26981 to 28031
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    22738 non-null  object
 1   crew    22738 non-null  object
 2   id      22738 non-null  int64
dtypes: int64(1), object(2)
memory usage: 710.6+ KB
None

3. Transformación de Datos (ETL)
(Tercera Celda - Desanidar Columnas y Llenar Valores Nulos)

In [15]:
# Desanidar columnas específicas
def desanidar_json(json_column):
    if isinstance(json_column, str):
        try:
            return eval(json_column)  # Evaluar como JSON si es posible
        except:
            return np.nan
    return json_column

df_movies['belongs_to_collection'] = df_movies['belongs_to_collection'].apply(desanidar_json)
df_movies['production_companies'] = df_movies['production_companies'].apply(desanidar_json)

# Rellenar valores nulos en 'revenue' y 'budget' con 0
df_movies['revenue'] = df_movies['revenue'].fillna(0)
df_movies['budget'] = df_movies['budget'].fillna(0)

(Cuarta Celda - Transformación de Fechas y Columnas Nuevas)

In [16]:
# 1. Desanidar algunos campos (opcional según lo necesites)

# 2. Rellenar valores nulos en 'revenue' y 'budget' con 0
df_movies['revenue'] = pd.to_numeric(df_movies['revenue'], errors='coerce').fillna(0)
df_movies['budget'] = pd.to_numeric(df_movies['budget'], errors='coerce').fillna(0)

# 3. Eliminar valores nulos en 'release_date'
df_movies = df_movies.dropna(subset=['release_date']).copy()

# 4. Formatear la columna 'release_date' al formato AAAA-mm-dd
df_movies.loc[:, 'release_date'] = pd.to_datetime(df_movies['release_date'], errors='coerce').dt.strftime('%Y-%m-%d')

# 5. Crear la columna 'release_year' extrayendo el año de la fecha de estreno
df_movies.loc[:, 'release_year'] = pd.to_datetime(df_movies['release_date']).dt.year

# 6. Crear la columna 'return' (retorno de inversión)
df_movies.loc[:, 'return'] = df_movies.apply(
    lambda x: x['revenue'] / x['budget'] if x['budget'] > 0 else 0, axis=1
)

# 7. Eliminar columnas que no serán utilizadas
columns_to_drop = ['video', 'imdb_id', 'adult', 'original_title', 'poster_path', 'homepage']
df_movies = df_movies.drop(columns=columns_to_drop, errors='ignore').copy()

# Verificar cambios
print("\nPrimeras filas después de las transformaciones:")
print(df_movies.head())

print("\nInformación del DataFrame después de las transformaciones:")
print(df_movies.info())

df_movies.to_csv("transformed_movies.csv", index=False)

Primeras filas después de las transformaciones:
                               belongs_to_collection      budget  \
0  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000.0
1                                                NaN  65000000.0
2  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0.0
3                                                NaN  16000000.0
4  {'id': 96871, 'name': 'Father of the Bride Col...         0.0

                                              genres     id original_language  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...    862                en
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   8844                en
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...  15602                en
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...  31357                en
4                     [{'id': 35, 'name': 'Comedy'}]  11862                en

                                            overview popularity  \
0  Led by Woody, Andy's toys live happily in his ...  21.946943
1  When siblings Judy and Peter discover an encha...  17.015539
2  A family wedding reignites the ancient feud be...    11.7129
3  Cheated on, mistreated and stepped on, the wom...   3.859495
4  Just when George Banks has recovered from his ...   8.387519

                                production_companies  \
0     [{'name': 'Pixar Animation Studios', 'id': 3}]
1  [{'name': 'TriStar Pictures', 'id': 559}, {'na...
2  [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
3  [{'name': 'Twentieth Century Fox Film Corporat...
4  [{'name': 'Sandollar Productions', 'id': 5842}...

                                production_countries release_date  \
0  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-10-30
1  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-15
2  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22
3  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-12-22
4  [{'iso_3166_1': 'US', 'name': 'United States o...   1995-02-10

       revenue  runtime                                   spoken_languages  \
0  373554033.0     81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1  262797249.0    104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2          0.0    101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3   81452156.0    127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4   76578911.0    106.0           [{'iso_639_1': 'en', 'name': 'English'}]

     status                                            tagline  \
0  Released                                                NaN
1  Released          Roll the dice and unleash the excitement!
2  Released  Still Yelling. Still Fighting. Still Ready for...
3  Released  Friends are the people who let you be yourself...
4  Released  Just When His World Is Back To Normal... He's ...

                         title  vote_average  vote_count  release_year  \
0                    Toy Story           7.7      5415.0        1995.0
1                      Jumanji           6.9      2413.0        1995.0
2             Grumpier Old Men           6.5        92.0        1995.0
3            Waiting to Exhale           6.1        34.0        1995.0
4  Father of the Bride Part II           5.7       173.0        1995.0

      return
0  12.451801
1   4.043035
2   0.000000
3   5.090760
4   0.000000

Información del DataFrame después de las transformaciones:
<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 45465
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget                 45379 non-null  float64
 2   genres                 45379 non-null  object
 3   id                     45379 non-null  object
 4   original_language      45368 non-null  object
 5   overview               44438 non-null  object
 6   popularity             45377 non-null  object
 7   production_companies   45379 non-null  object
 8   production_countries   45379 non-null  object
 9   release_date           45376 non-null  object
 10  revenue                45379 non-null  float64
 11  runtime                45130 non-null  float64
 12  spoken_languages       45376 non-null  object
 13  status                 45296 non-null  object
 14  tagline                20398 non-null  object
 15  title                  45376 non-null  object
 16  vote_average           45376 non-null  float64
 17  vote_count             45376 non-null  float64
 18  release_year           45376 non-null  float64
 19  return                 45379 non-null  float64
dtypes: float64(7), object(13)
memory usage: 7.3+ MB
None

(Quinta Celda - Eliminar Columnas y Realizar el Merge)

In [17]:
# Verificar columnas disponibles antes de intentar eliminarlas
print("Columnas actuales del DataFrame:", df_movies.columns)

# Eliminar columnas innecesarias (ignorar errores si alguna no existe)
columns_to_drop = ['video', 'imdb_id', 'adult', 'original_title', 'poster_path', 'homepage']
df_movies = df_movies.drop(columns=columns_to_drop, errors='ignore')

# Convertir 'id' a numérico y realizar el merge con df_credits
df_credits['id'] = pd.to_numeric(df_credits['id'], errors='coerce')
df_movies['id'] = pd.to_numeric(df_movies['id'], errors='coerce')

# Realizar el merge
df_merged = pd.merge(df_movies, df_credits, on='id', how='left')

Columnas actuales del DataFrame: Index(['belongs_to_collection', 'budget', 'genres', 'id', 'original_language',
       'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'release_year', 'return'],
      dtype='object')

4. Implementación de la API
(Sexta Celda - Configuración de la API)

In [18]:
# Cargar el dataset transformado
df = pd.read_csv("transformed_movies.csv", low_memory=False)
# Crear la aplicación FastAPI
app = FastAPI()

# Habilitar CORS (opcional)
origins = ["*"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

(Séptima Celda - Endpoints de la API)
python
Copiar código

In [19]:
@app.get("/")
def home():
    return {"message": "Bienvenido a la API de Películas"}

@app.get("/cantidad_filmaciones_mes/{mes}")
def cantidad_filmaciones_mes(mes: str):
    meses = {
        "enero": 1, "febrero": 2, "marzo": 3, "abril": 4,
        "mayo": 5, "junio": 6, "julio": 7, "agosto": 8,
        "septiembre": 9, "octubre": 10, "noviembre": 11, "diciembre": 12
    }
    mes_num = meses.get(mes.lower())
    if mes_num:
        cantidad = df[pd.to_datetime(df['release_date']).dt.month == mes_num].shape[0]
        return {"mes": mes, "cantidad": cantidad}
    return {"error": "Mes inválido"}

@app.get("/cantidad_filmaciones_dia/{dia}")
def cantidad_filmaciones_dia(dia: str):
    dias = {
        "lunes": 0, "martes": 1, "miércoles": 2, "jueves": 3,
        "viernes": 4, "sábado": 5, "domingo": 6
    }
    dia_num = dias.get(dia.lower())
    if dia_num is not None:
        cantidad = df[pd.to_datetime(df['release_date']).dt.weekday == dia_num].shape[0]
        return {"dia": dia, "cantidad": cantidad}
    return {"error": "Día inválido"}

@app.get("/score_titulo/{titulo}")
def score_titulo(titulo: str):
    resultado = df[df['title'].str.contains(titulo, case=False, na=False)]
    if not resultado.empty:
        pelicula = resultado.iloc[0]
        return {
            "titulo": pelicula['title'],
            "año": pelicula['release_year'],
            "score": pelicula['popularity']
        }
    return {"error": "Película no encontrada"}

@app.get("/votos_titulo/{titulo}")
def votos_titulo(titulo: str):
    resultado = df[df['title'].str.contains(titulo, case=False, na=False)]
    if not resultado.empty:
        pelicula = resultado.iloc[0]
        if pelicula['vote_count'] >= 2000:
            return {
                "titulo": pelicula['title'],
                "cantidad_votos": pelicula['vote_count'],
                "promedio_votos": pelicula['vote_average']
            }
        return {"error": "La película no tiene suficientes votos"}
    return {"error": "Película no encontrada"}

(Octava Celda - Continuación de Endpoints)

In [20]:
@app.get("/get_actor/{nombre_actor}")
def get_actor(nombre_actor: str):
    actores = df[df['cast'].str.contains(nombre_actor, case=False, na=False)]
    if not actores.empty:
        retorno_total = actores['return'].sum()
        cantidad = actores.shape[0]
        promedio = retorno_total / cantidad if cantidad > 0 else 0
        return {
            "actor": nombre_actor,
            "cantidad_filmaciones": cantidad,
            "retorno_total": retorno_total,
            "promedio_retorno": promedio
        }
    return {"error": "Actor no encontrado"}

@app.get("/get_director/{nombre_director}")
def get_director(nombre_director: str):
    directores = df[df['crew'].str.contains(nombre_director, case=False, na=False)]
    if not directores.empty:
        peliculas = []
        for _, row in directores.iterrows():
            peliculas.append({
                "titulo": row['title'],
                "fecha_lanzamiento": row['release_date'],
                "retorno": row['return'],
                "costo": row['budget'],
                "ganancia": row['revenue']
            })
        retorno_total = directores['return'].sum()
        return {
            "director": nombre_director,
            "retorno_total": retorno_total,
            "peliculas": peliculas
        }
    return {"error": "Director no encontrado"}

:

5. Ejecución Local
(Novena Celda)

In [ ]:
# Usar nest_asyncio para permitir la ejecución en Jupyter Notebook
nest_asyncio.apply()

# Ejecutar la aplicación
run(app, host="0.0.0.0", port=8000)

INFO:     Started server process [1588]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

INFO:     127.0.0.1:57190 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:57190 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:57190 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:57190 - "GET /openapi.json HTTP/1.1" 200 OK